---
- name: Download CNI plugins
  ansible.builtin.get_url:
    url: "https://github.com/containernetworking/plugins/releases/download/{{ cni_plugins_version }}/cni-plugins-linux-arm64-{{ cni_plugins_version }}.tgz"
    dest: "/tmp/cni-plugins-linux-arm64-{{ cni_plugins_version }}.tgz"

- name: Create CNI bin directory
  ansible.builtin.file:
    path: /opt/cni/bin
    state: directory
    mode: '0755'

- name: Extract CNI plugins
  ansible.builtin.unarchive:
    src: "/tmp/cni-plugins-linux-arm64-{{ cni_plugins_version }}.tgz"
    dest: /opt/cni/bin
    remote_src: yes

- name: Remove CNI plugins archive
  ansible.builtin.file:
    path: "/tmp/cni-plugins-linux-arm64-{{ cni_plugins_version }}.tgz"
    state: absent
