---
cloud_init:
  work_dir: /workspace/cloud-init
  instance_id: raspberry-pi-5
  hostname: "raspberry-pi-5"
  username: admin
  password_hash: "{{ 'admin' | password_hash('sha512') }}"
  network_interface: eth0
  ip_addresses:
    - 192.168.0.80/24
  gateway: 192.168.0.1
  nameservers:
    - 1.1.1.1
    - 8.8.8.8

rpi_os:
  base_url: https://downloads.raspberrypi.com
  release_date: 2025-12-04
  variant: lite
  arch: arm64
  os_name: raspios
  os_version: trixie
  file_extension: img.xz
  image_compressed: "{{ rpi_os.os_name }}-{{ rpi_os.os_version }}-{{ rpi_os.arch }}-{{ rpi_os.variant }}.{{ rpi_os.file_extension }}"
  image: "{{ rpi_os.os_name }}-{{ rpi_os.os_version }}-{{ rpi_os.arch }}-{{ rpi_os.variant }}.img"
  download_url: "{{ rpi_os.base_url }}/{{ rpi_os.os_name }}_{{ rpi_os.variant }}_{{ rpi_os.arch }}/images/{{ rpi_os.os_name }}_{{ rpi_os.variant }}_{{ rpi_os.arch }}-{{ rpi_os.release_date }}/{{ rpi_os.release_date }}-{{ rpi_os.image_compressed }}"

mount:
  mount_point: /workspace/mnt
