---
- name: Create SSH key pair
  community.crypto.openssh_keypair:
    path: "{{ cloud_init.work_dir }}/id_rsa"
    size: 4096

- name: Read public SSH key
  ansible.builtin.slurp:
    src: "{{ cloud_init.work_dir }}/id_rsa.pub"
  register: public_ssh_key
