---
- name: Download virtctl
  ansible.builtin.get_url:
    url: "https://github.com/kubevirt/kubevirt/releases/download/{{ virtctl_version }}/virtctl-{{ virtctl_version }}-linux-arm64"
    dest: "/tmp/virtctl"
    mode: '0755'

- name: Install virtctl
  ansible.builtin.copy:
    src: "/tmp/virtctl"
    dest: "/usr/local/bin/virtctl"
    owner: root
    group: root
    mode: '0755'
    remote_src: yes

- name: Remove temporary virtctl
  ansible.builtin.file:
    path: "/tmp/virtctl"
    state: absent
